### ISSUE TITLE
Kafka Error

### ISSUE THREAD

**Issue by sulthonzh** [andeya/pholcus#52]
```
[E] kafka server: In the middle of a leadership election, there is currently no leader for this partition and hence it is unavailable for writes.
2017/08/07 14:25:38 [E] circuit breaker is open
2017/08/07 14:25:38 [E] circuit breaker is open
```

hi there i got this error, when use kafka output

**Comment by sundy-li** [comment]
Hi, this is the kafka server error, not the sarama client error, and when this error occurs,  just use ` $KAFKA_HOME/bin/kafka-topics.sh --describe --topic $topic --zookeeper $zk` command to show the status of the topic, and you will see the leader is -1 for this partition.

Possiable  ways to solve it
1. I suggest you to create the topic by manual to specify the partition number and the  replicate number  instead of auto-create by client with default value

2. modify the kafka server config, improve the zookeeper connect timeout value and then  restart kafka server

3. Maybe your system io is too high, use `iostat`to debug about it

**Comment by sulthonzh** [comment]
@sundy-li OK thanks for this,

**Comment by sulthonzh** [comment]
https://gist.github.com/loggerhead/4c8ad3325d95ecd15562c80c1f818ef8 i have try this



but not working, step 4 ... 7, where should i run steps? at docker exec? or in local computer?

**Comment by sundy-li** [comment]
@sulthonzh   
1. I recommend you not to install kafka cluster by docker, try the install guide here `https://kafka.apache.org/quickstart`

2. If you still want to  install kafka cluster by docker,I have made a  docker script before, try `https://github.com/sundy-li/kafka-cluster`
